version: '3'

services:
    risks: &base_app
        image: "${IMAGE}"
        command: python -m prozorro.risks.api
        container_name: risks-api
        environment:
            MONGODB_URL: 'mongodb://root:example@mongo:27017/?replicaSet=rs0'
            PYTHONUNBUFFERED: '1'
        ports:
            - 8080:8080
        volumes:
            - ./src/prozorro:/app/prozorro
            - ./tests:/prozorro/tests
            - ./swagger:/swagger
        depends_on:
            - mongo
            - tenders-crawler
            - contracts-crawler

    tenders-crawler:
        image: "${IMAGE}"
        container_name: risks-tenders-crawler
        environment:
            MONGODB_URL: 'mongodb://root:example@mongo:27017/?replicaSet=rs0'
            PYTHONUNBUFFERED: '1'
            MONGODB_STATE_ID: 'prozorro-tenders-risks'
            API_OPT_FIELDS: 'status,auctionPeriod,lots,next_check'
            PUBLIC_API_HOST: 'https://api.prozorro.gov.ua'
            FORWARD_CHANGES_COOLDOWN_SECONDS: '36000'  # 10 hours in seconds
            BACKWARD_OFFSET: '1423058400.69246'  # 2015-02-23T12:00:00.756010+02:00
            FORWARD_OFFSET: '1672524000.0'  # 2023-01-01T00:00:00+02:00
        command: python -m prozorro.risks.crawlers.tenders_crawler
        volumes:
            - ./src/prozorro:/app/prozorro

    contracts-crawler:
        image: "${IMAGE}"
        container_name: risks-contracts-crawler
        environment:
            MONGODB_URL: 'mongodb://root:example@mongo:27017/?replicaSet=rs0'
            PYTHONUNBUFFERED: '1'
            MONGODB_STATE_ID: 'prozorro-contracts-risks'
            API_RESOURCE: 'contracts'
            PUBLIC_API_HOST: 'https://api.prozorro.gov.ua'
            FORWARD_CHANGES_COOLDOWN_SECONDS: '36000'  # 10 hours in seconds
            BACKWARD_OFFSET: '1423058400.69246'  # 2015-02-23T12:00:00.756010+02:00
            FORWARD_OFFSET: '1672524000.0'  # 2023-01-01T00:00:00+02:00
            LOCK_PROCESS_NAME: 'contracts_crawler_lock'
        command: python -m prozorro.risks.crawlers.contracts_crawler
        volumes:
            - ./src/prozorro:/app/prozorro

    mongo:
        image: 'bitnami/mongodb:4.4.3'
        environment:
            MONGODB_ADVERTISED_HOSTNAME: mongo
            MONGODB_ROOT_PASSWORD: example
            MONGODB_REPLICA_SET_MODE: primary
            MONGODB_REPLICA_SET_NAME: rs0
            MONGODB_REPLICA_SET_KEY: replicaSetKey
        ports:
            - 27017:27017

    frontend:
        image: "${IMAGE_FRONTEND}"
        ports:
            - 9090:80

    risks-test-integration: &test_app
        <<: *base_app
        image: "${IMAGE_TEST}"
        container_name: risks-test-integration
        depends_on:
          - mongo
        volumes:
            - ./src/prozorro:/app/prozorro
            - ./tests:/prozorro/tests
            - ./swagger:/swagger
            - ./pytest.ini:/app/pytest.ini
