[project]
name = "prozorro-risks"
version = "1.0.40"
description = "Risks detection project to monitor active tenders in CDB"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "aiohttp>=3.6.2,<4",
    "pymongo>=4.13,<5",
    "aiohttp-swagger3>=0.9.0,<1",
    "python-json-logger>=2.0.2,<5",
    "sentry-sdk>=2.62.0,<3",
    "pydantic>=2.13.4,<3",
    "ciso8601>=2.3.3,<3",
    "aiocache>=0.12.3,<1",
    "prozorro_crawler",
    "dateorro",
    "standards",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-aiohttp==1.0.5",
    "pytest-asyncio==0.25.0",
    "pytest-cov",
    "parameterized",
    "ruff",
    "mypy",
]

[tool.ruff]
exclude = [".git", ".venv", "__pypackages__", "build", "dist", "venv", "tests"]
line-length = 120
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.mypy]
ignore_missing_imports = true

[tool.uv.sources]
prozorro_crawler = { git = "https://github.com/ProzorroUKR/prozorro_crawler.git", rev = "2.3.0" }
dateorro = { git = "https://github.com/ProzorroUKR/dateorro.git", rev = "0.0.3" }
standards = { git = "https://github.com/ProzorroUKR/standards.git", rev = "1.0.257" }
