tags:
- Helpers
description: Get filter values with list of unique regions and risk rules
operationId: get_filter_values
produces:
- application/json
responses:
  "200":
    description: successful operation
    content:
      application/json:
        schema:
          type: object
          properties:
            regions:
              type: array
              items:
                type: string
                description: Region name
            risk_rules:
              type: array
              items:
                type: string
                description: Risk rules
