tags:
- Helpers
description: Get a list of unique region values
operationId: get_region_values
produces:
- application/json
responses:
  "200":
    description: successful operation
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Region name
              value:
                type: string
                description: Region value
