apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prozorro.risks.fullname" . }}-contracts-crawler
  labels:
{{ include "prozorro.risks.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.contracts-crawler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prozorro.risks.name" . }}-contracts-crawler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prozorro.risks.name" . }}-contracts-crawler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-contracts-crawler
          image: "{{ .Values.contracts-crawler.image.repository }}:{{ .Values.contracts-crawler.image.tag }}"
          imagePullPolicy: {{ .Values.contracts-crawler.image.pullPolicy }}
          command: ["python", "-m", "prozorro.risks.contracts_crawler"]
          env:
            - name: MONGODB_URL
              value: 'mongodb://root:pass@mongodb-risks.data.svc.cluster.local:27017'
            - name: PUBLIC_API_HOST
              value: 'http://api.master.k8s.prozorro.gov.ua'
            - name: MONGODB_STATE_ID
              value: 'prozorro-contracts-risks'
            - name: BACKWARD_OFFSET
              value: '1423058400.69246'
            - name: FORWARD_OFFSET
              value: '1672524000.0'
            - name: FORWARD_CHANGES_COOLDOWN_SECONDS
              value: '36000'
            - name: API_RESOURCE
              value: 'contracts'
            - name: LOCK_PROCESS_NAME
              value: 'contracts_crawler_lock'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
