apiVersion: v1
kind: Service
metadata:
  name: {{ template "prozorro.risks.fullname" . }}-frontend
  labels:
{{ include "prozorro.risks.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prozorro.risks.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
