apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prozorro.risks.fullname" . }}-tenders-crawler
  labels:
{{ include "prozorro.risks.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.tenders_crawler.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prozorro.risks.name" . }}-tenders-crawler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "prozorro.risks.name" . }}-tenders-crawler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-tenders-crawler
          image: "{{ .Values.tenders_crawler.image.repository }}:{{ .Values.tenders_crawler.image.tag }}"
          imagePullPolicy: {{ .Values.tenders_crawler.image.pullPolicy }}
          command: ["python", "-m", "prozorro.risks.crawlers.tenders_crawler"]
          env:
            - name: MONGODB_URL
              value: '{{ .Values.config.mongodb_uri }}'
            - name: SENTRY_DSN
              value: '{{ .Values.config.sentry_dsn }}'
            - name: PUBLIC_API_HOST
              value: '{{ .Values.config.public_api_host }}'
            - name: MONGODB_STATE_ID
              value: 'prozorro-tenders-risks'
            - name: BACKWARD_OFFSET
              value: '{{ .Values.config.backward_offset }}'
            - name: FORWARD_OFFSET
              value: '{{ .Values.config.forward_offset }}'
            - name: FORWARD_CHANGES_COOLDOWN_SECONDS
              value: '{{ .Values.config.forward_changes_cooldown_seconds }}'
            - name: TEST_MODE
              value: '{{ .Values.config.test_mode }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
