config:
  mongodb_uri: 'mongodb://root:5x0A2CfpE8HdUGF@mongodb-risks.data.svc.cluster.local:27017'
  sentry_dsn: 'http://c921e523b5384eb990c5cd2737d2aa79@sentry.dc.prozorro.gov.ua/55'
  public_api_host: 'http://api.master.k8s.prozorro.gov.ua'
  backward_offset: '1423058400.69246'
  forward_offset: '1730325600.0'
  delay_forward_offset: '1730325600.0'
  forward_changes_cooldown_seconds: '0'
  delay_forward_changes_cooldown_seconds: '2678'
  sleep_forward_changes_seconds: '2678'
  test_mode: 'True'
  api_limit: '1'

api:
  replicaCount: 1
  image:
    repository: docker-registry.prozorro.gov.ua/cdb/prozorro-risks
    tag: latest
    pullPolicy: Always

tenders_crawler:
  replicaCount: 1
  image:
    repository: docker-registry.prozorro.gov.ua/cdb/prozorro-risks
    tag: latest
    pullPolicy: Always

contracts_crawler:
  replicaCount: 1
  image:
    repository: docker-registry.prozorro.gov.ua/cdb/prozorro-risks
    tag: latest
    pullPolicy: Always

delay_crawler:
  replicaCount: 1
  image:
    repository: docker-registry.prozorro.gov.ua/cdb/prozorro-risks
    tag: latest
    pullPolicy: Always

frontend:
  replicaCount: 1
  image:
    repository: docker-registry.prozorro.gov.ua/cdb/prozorro-risks/prozorro-risks-frontend
    tag: latest
    pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: risks.latest.k8s.prozorro.gov.ua
      paths:
        - path: /
          pathType: ImplementationSpecific
          service: frontend
        - path: /api
          pathType: ImplementationSpecific
          service: api
  tls: []

imagePullSecrets:
  - name: prozorro-gitlab

nameOverride: ""
fullnameOverride: ""
